- client/src/components/Overview/__test__/Overview.test.js
- package-lock.json
- package.json
- removed enzyme from package.json
- added react testing library and necessary dependencies
- ensured test suite and syntax provided worked as expected
- updated the overview test suite to have 2 passing tests
doc for reference: https://testing-library.com/docs/
> added react testing library, migrated from enzyme

- .gitignore
- client/src/components/Questions.jsx
- client/src/components/Questions/QuestionsComponents/QuestionsList.jsx
- client/src/index.jsx
- package.json
- server/api-helpers/CartAPI.js
- server/api-helpers/InteractionsAPI.js
- server/api-helpers/ProductsAPI.js
- server/api-helpers/QuestionsAPI.js
- server/api-helpers/ReviewsAPI.js
- server/index.js
I believe I have officially rebased and pushed the server up.
> basic server and helper-funcs

- .gitignore
- client/src/components/Questions.jsx
- client/src/components/Questions/QuestionsComponents/Answer.jsx
- client/src/components/Questions/QuestionsComponents/AnswerList.jsx
- client/src/components/Questions/QuestionsComponents/Question.jsx
- client/src/components/Questions/QuestionsComponents/QuestionsList.jsx
- client/src/components/Questions/QuestionsComponents/SearchQuestions.jsx
- client/src/index.jsx
- package.json
- server/api-helpers/CartAPI.js
- server/api-helpers/InteractionsAPI.js
- server/api-helpers/ProductsAPI.js
- server/api-helpers/QuestionsAPI.js
- server/api-helpers/ReviewsAPI.js
- server/index.js
Apologies for my pastiche PR. Sprinting hard. 
Now has functionality for search. Questions list still needs report & help functionality.
> Questions list & search functionality

- client/dist/index.html
- client/dist/yourOutfit.css
- client/src/components/Related.jsx
- client/src/components/Related/ComparisonModal.jsx
- client/src/components/Related/OutfitCarousel.jsx
- client/src/components/Related/RelatedCarousel.jsx
- client/src/components/Related/RelatedProductCard.jsx
- client/src/components/Related/YourOutfit.jsx
- client/src/components/Reviews/ReviewTile.jsx
- client/src/index.jsx
- package-lock.json
- server/index.js
-Create base for team review for modal component
-CSS is good boilder plate, looks nice
-Key takeaways: place component in most effective location and utilize useState and useEffect to pass modal component conditional viewing
> Create relevant modal (pop up)

- client/dist/index.html
- client/dist/related.css
- client/dist/reviews.css
- client/src/components/Reviews/RatingsBreakdown.jsx
- client/src/components/Reviews/ReviewTile.jsx
- built out majority of the functionality for ratings breakdown
- rating distribution bar functioning but made to the wireframe instead of BRD (percentage filled based on mode vs based on total reviews)
- missing sorting by rating feature
> Ratings breakdown

- client/src/components/Overview.jsx
- client/src/components/Overview/ImageGallery/DefaultGallery.jsx
- client/src/components/Overview/ImageGallery/ExpandedGallery.jsx
- client/src/components/Overview/ProductInformation/ToggleOutfitStar.jsx
- client/src/components/Overview/__test__/OverviewLoads.test.js
- client/src/components/Reviews/RatingsBreakdown.jsx
- client/src/index.jsx
- server/api-helpers/ReviewsAPI.js
- server/index.js
- ensure images render properly for the default view
- ensure thumbnails render for default view
- toggle between images setup
- toggle between default view and expanded view (need to add an overlay)
- update unit tests to account for updated content and props
**Additional:**
- update toggleStar for the outfit toggle (note this @AaronSMiller - open to updates as needed!)
- note that I made some minor updates on my end to the reviews files per Thomas' recent PR to avoid errors while developing this portion -- double-check this for accuracy
> Overview Views (Subcomponent 4 - initial setup)

- client/src/components/Overview/ProductInformation/ToggleOutfitStar.jsx
- client/src/index.jsx
- add star image to star button
- add console.log to show star button clicked
- minor tweaks
> add minor updates prior to presentation

- client/src/components/Overview/ProductInformation/StarsReviews.jsx
- client/src/components/Overview/ProductInformation/__test__/OverviewProductInformation.test.js
- client/src/components/Reviews.jsx
- updated the stars and reviews section
- add link to the reviews section
- update stars functionality and confirmed semi-filled stars are working and match the average rating
- add unit test to confirm that this won't render when no reviews are present
> Overview - Stars & Reviews

- client/dist/overview.css
- client/src/components/Overview.jsx
- client/src/components/Overview/ProductInformation/Price.jsx
- client/src/components/Overview/ProductInformation/StarsReviews.jsx
- client/src/components/Overview/ProductInformation/__test__/OverviewProductInformation.test.js
- client/src/components/Reviews.jsx
- ensure ability to include sale price, conditionally
- add effects for sale price when present (sales price in red, original price struck through)
- add 3 unit tests to check for sales price and price section rendering
> Overview - Sale Price

- client/dist/related.css
- client/src/components/Related.jsx
- client/src/components/Related/OutfitCarousel.jsx
- client/src/components/Related/RelatedCarousel.jsx
- client/src/components/Related/RelatedProductCard.jsx
- client/src/components/Related/YourOutfit.jsx
- client/src/components/Related/YourOutfitCard.jsx
- client/src/index.jsx
-Fix issues relating to inability to update state in related and outfit carousel
-Utilized dependency array in useEffect to accomplish this (see RelatedProductCard / YourOutfitCard)
-Add functionality to remove items in outfit array and conditionally
> Related and Outfit Carousel Functionality Updates

- client/src/components/Overview.jsx
- client/src/components/Overview/ProductInformation/ToggleOutfitStar.jsx
- client/src/components/Overview/__test__/OverviewLoads.test.js
- client/src/index.jsx
- updated functionality to mirror @AaronSMiller's outfit carousel method
- updated a test to ensure passing as expected with updated functionality
> toggleStar working as expected

- client/src/components/Reviews/ReviewPhotoModal.jsx
- client/src/components/Reviews/ReviewPhotoWrapper.jsx
- client/src/components/Reviews/ReviewTile.jsx
- client/src/index.jsx
- implement HOC wrapper to take review images and add modal functionality
> Reviews modal

- client/src/components/Reviews.jsx
- client/src/components/Reviews/AddReviewForm.jsx
- client/src/components/Reviews/AddReviewStars.jsx
- client/src/components/Reviews/AddReviewWrapper.jsx
- client/src/components/Reviews/OverallReviewStars.jsx
- client/src/components/Reviews/ReviewsList.jsx
- client/src/index.jsx
- add review form is on a modal
- stars for overall review rating are partially mapped
- characteristics radio button, explicit rating description, and states are working
> progress on adding review functionality

- client/src/components/Overview/AddToCart/Cart.jsx
- client/src/components/Overview/AddToCart/SizeQuantity.jsx
- client/src/components/Overview/StyleSelector/Style.jsx
- package-lock.json
- add minor functionality to the select size section when no size is selected upon clicking "Add to Cart"
- confirmed tests still working properly
> Overview update select size alert and functionality

- client/dist/questions.css
- client/src/components/Questions/QuestionsComponents/Question.jsx
- client/src/index.jsx
Fixed deleted div tag issue in index.jsx
> breaking DivTag and questions scroll fixed

- client/dist/yourOutfit.css
- client/src/components/Related/OutfitCarousel.jsx
-Add logic for conditional rendering in outfit carousel
-Css updates
> Related- Outfit Carousel - Logic

- client/dist/related.css
- client/dist/yourOutfit.css
- client/src/components/Related/Related.test.js
- client/src/components/Related/YourOutfit.jsx
- client/src/index.jsx
-Update related tests
-Update related CSS
> Related- Update Test

- client/src/components/Related/Related.test.js
- client/src/components/Related/RelatedProductCard.jsx
- client/src/components/Related/YourOutfitCard.jsx
> Related - add additional tests

- client/src/components/Overview/AddToCart/SizeQuantity.jsx
- client/src/components/Overview/AddToCart/__test__/OverviewAddToCart.test.js
- client/src/components/Overview/ProductInformation/__test__/OverviewProductInformation.test.js
- client/src/components/Overview/StyleSelector/__test__/OverviewStyleSelector.test.js
- package.json
- added additional tests
- made minor updates to my functionality for passing tests
- made notes for more complex tests to go back and add or update later
> Overview update testsuite3

- client/src/components/Overview/AddToCart/Cart.jsx
- client/src/components/Overview/AddToCart/SizeQuantity.jsx
- client/src/components/Overview/ImageGallery/DefaultGallery.jsx
- client/src/components/Overview/ImageGallery/ExpandedGallery.jsx
- client/src/components/Overview/ProductInformation/StarsReviews.jsx
- client/src/components/Overview/StyleSelector/Style.jsx
- added "id" and "widgetname" attributes to meaningful, clickable items in the Overview section
> overview click tracking implementation

- client/src/components/Questions/QuestionsComponents/AddAnswerModal.jsx
- client/src/components/Questions/QuestionsComponents/AddQuestionModal.jsx
- client/src/components/Questions/QuestionsComponents/Answer.jsx
- client/src/components/Questions/QuestionsComponents/Question.jsx
- client/src/components/Questions/__test__/Questions.test.js
- package-lock.json
Added alt tags, added some testing for search. Finished tech debt for responses.
> Finishing testing

- package-lock.json
- package.json
- server/index.js
> add initial text compression

- client/src/atelier.jsx
- client/src/components/Reviews.jsx
- client/src/components/Reviews/AddReviewForm.jsx
- client/src/components/Reviews/AddReviewWrapper.jsx
- client/src/components/Reviews/BreakdownSlider.jsx
- client/src/components/Reviews/ProductBreakdown.jsx
- client/src/components/Reviews/RatingsBreakdown.jsx
- client/src/components/Reviews/RatingsColumn.jsx
- client/src/components/Reviews/ReviewPhotoWrapper.jsx
- client/src/components/Reviews/ReviewTile.jsx
- client/src/components/Reviews/ReviewsList.jsx
- client/src/components/shared/StarRating/StarRating.jsx
- client/src/styles/reviews.css
- package-lock.json
- package.json
- added cloudinary API for photo upload functionality
- fixed styling
- fixed async bug fixes
- added rating filtering
> Ratings and Reviews Features

- client/src/components/Overview/ImageGallery/DefaultGallery.jsx
- client/src/components/Overview/ImageGallery/ExpandedGallery.jsx
- client/src/components/Overview/ImageGallery/ImageGalleryCSS.jsx
- client/src/components/Overview/ProductInformation/StarsReviews.jsx
- client/src/components/shared/StarRating/StarRating.jsx
- client/src/styles/overview.css
- package-lock.json
- package.json
- identified a possible zoom option, though not the ideal option
> Overview expandedzoom
